### ISSUE TITLE
100M的宽带连10M都没跑到啊

### ISSUE THREAD

**Issue by pizixi** [zhijikejian/vnet-v2#1]
![image](https://github.com/user-attachments/assets/eb995cbb-9524-4ae3-8013-ca294a61002c)

**Comment by zhijikejian** [comment]
不好意思，我没做速度测试，可以试试更改read缓存

// 数据包的头协议定义
const Buffersize = 1024 * 5 // read缓存容量 // 小于10的Msglensize次方
const Msglensize = 4        // 数据包长度标记容量 // 大于等于Buffersize所需的位数
